baseurl: /chessington
include: ['_pages']
sass:
sass_dir: _sass
prose:
  rooturl: '_pages'
  siteurl: 'http://mcooke.github.io/chessington/'
  metadata:
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
      - name: "permalink"
        field:
          element: "text"
